### PR TITLE
Normalize imported markdown field values

### LINKED ISSUE #206: Markdown importer should attempt to convert non-text fields to the correct value
## Expected Behavior
If a field has a schema type of boolean for example, I would expect the imported value to be parsed into a boolean

## Actual Behavior
The values are imported as plain text

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Browser:
- OS:

## References

---

Before submitting this issue, please check that this issue is not a duplicate.
If there is another issue describing the same problem please add your
information to that issue's comments.

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Fixes #206

change-type: minor

### CODE REVIEW

File: src/services/importer.js [hunk 1]
```diff
@@ -24,7 +25,13 @@ export const convert = (schema, markdown) => {
       const [segmentKey] = segment.match(/^.*$/m)
       const segmentValue = segment.replace(segmentKey, '')
       if (segmentKey.trim().length) {
```
Comment (thgreasi) [inline src/services/importer.js]: I guess that this could just be `if (segmentKey.trim())`, but it's already there and works so forget it

File: test/importer.spec.js [hunk 2]
```diff
@@ -19,6 +21,65 @@ const schema = [
   }
 ]
 
+const schema2 = [
+  {
+    name: 'Title',
```
Comment (thgreasi) [inline test/importer.spec.js]: Purely a nice to have, could we add one more that is not title, just to cover that case as well?
