### PR TITLE
Make anchor links use UUID instead of title

### LINKED ISSUE #245: Permalink changes if title changes
## Expected Behavior
Permalink is perma, so we can reference it elsewhere in the resinsphere.

## Actual Behavior
Permalink changes if the title is edited

## Steps to Reproduce the Problem

1. Note permalink to entry
1. Change title text
1. Note new permalink

## Specifications

- Browser:
- OS:

## References

---

Before submitting this issue, please check that this issue is not a duplicate.
If there is another issue describing the same problem please add your
information to that issue's comments.

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Fixes #245

change-type: patch

### CODE REVIEW

File: src/components/document-viewer/doc-fragment.jsx [hunk 1]
```diff
@@ -412,7 +412,7 @@ class DocFragment extends Component {
             </Flex>
           )}
           <h2>
-            <AnchorLink text={this.props.content[this.getTitleKey()]} />
+            <AnchorLink text={this.props.content.getUuid()} />
```
Comment (lurch) [inline src/components/document-viewer/doc-fragment.jsx]: I guess something similar also ought to be done on line 429?

Comment (LucianBuzzo) [reply src/components/document-viewer/doc-fragment.jsx]: good spot!

File: src/components/document-viewer/doc-fragment.jsx [hunk 2]
```diff
@@ -425,9 +425,7 @@ class DocFragment extends Component {
                   {title.indexOf(PENSIEVE_IMPORTED_COPY_FIELD_KEY) === -1 && (
                     <h3>
                       <AnchorLink
-                        text={
-                          this.props.content[this.getTitleKey()] + '-' + title
-                        }
+                        text={this.props.content.getUuid() + '-' + title}
```
Comment (lurch) [inline src/components/document-viewer/doc-fragment.jsx]: Does something clever need to be done here (e.g. appending an auto-incrementing number), in case the entry with a given `Uuid` has two headers with the identical `title` ?
(or is that guaranteed to never happen?)

P.S. I obviously know nothing about the framework being used here (and it's outside the scope of this particular PR), but I wonder if `<AnchorLink href=...>` (or `<AnchorLink id=...>`) would have made it more obvious what this is doing than `<AnchorLink text=...>` ? (people might assume that a `text` attribute is what gets displayed to the user?)

Comment (LucianBuzzo) [reply src/components/document-viewer/doc-fragment.jsx]: The data structure used for entries guarantees that you never have a duplicated field header on an entry. Using an attribute like `hash` or `fragment` would be more semantically correct, but is beyond the scope of this PR.

Comment (lurch) [reply src/components/document-viewer/doc-fragment.jsx]: > The data structure used for entries guarantees that you never have a duplicated field header on an entry.

Are you sure? How does that account for URLs like:
https://resin-io.github.io/scratchpad/#2aa7ca4c-d424-11e7-a9ca-d3e1e018ddf6-treatment-after-resinos-v1-1-2--this-issue-shouldn-t-happen-as-dnsmasq-is-used-as-the-resolver--

Comment (LucianBuzzo) [reply src/components/document-viewer/doc-fragment.jsx]: @lurch I don't understand what you mean? Does the link go to a duplicated header?

Comment (lurch) [reply src/components/document-viewer/doc-fragment.jsx]: Sorry Lucian, my mistake - I thought such a long anchor-link was coming from the ability to use Markdown text inside entries, but looking at the [YAML file](https://github.com/resin-io/scratchpad/blob/master/scratchpad.yaml#L1012) I see that this actually _is_ the name of one of the fields in that entry.
So I guess what you were saying earlier is that even _with_ user-defined fields, pensieve doesn't allow multiple fields in the same entry to have the same name? (apologies if I'm using the wrong terminology)

Comment (LucianBuzzo) [reply src/components/document-viewer/doc-fragment.jsx]: @lurch the entries are esentially defined as JSON objects where the key is the subheader, so as soon as you add a 'header' that already exists, it just overwrites the pre-existing one.

Comment (lurch) [reply src/components/document-viewer/doc-fragment.jsx]: How does that manifest itself in the pensieve web-interface? Could a user accidentally overwrite an existing field by creating a new field with the same name? (If yes, should I create a new issue for that?)

Comment (lurch) [reply src/components/document-viewer/doc-fragment.jsx]: I've just tested this in the pensieve web-interface myself, and if you add a user-defined field that has the same name as an existing field, then Pensieve doesn't display any error or warning, and any contents in the existing field get silently discarded :-(  I'll add an issue...
