### PR TITLE
Display error message data from response if it is available

### LINKED ISSUE #282: Display error messages when failing to save to github

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Fixes #282

Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>

### CODE REVIEW

File: src/services/notifications.js [hunk 1]
```diff
@@ -49,8 +49,15 @@ export const dismiss = id => {
   store.dispatch(actions.setAlerts(alerts.filter(a => a.id !== id)))
 }
 
-export const error = message => {
-  createNotification('error', message)
+export const error = error => {
+  console.log({ error })
```
Comment (lurch) [inline src/services/notifications.js]: Is this `console.log` _supposed_ to be left in here?

Comment (LucianBuzzo) [reply src/services/notifications.js]: Dang it! No its not :smile: good catch @lurch :+1:
