### PR TITLE
Fix bug that can occur with production version of Pensieve diff

### LINKED ISSUE #213: Schema edits cannot be saved
## Expected Behavior
Saving a schema edit should work

## Actual Behavior
Nothing happens, and the following error appears in the console
```
pensieve.js?1512146626676:formatted:8589 Uncaught TypeError: a is not a function
    at pensieve.js?1512146626676:formatted:8589
    at pensieve.js?1512146626676:formatted:3451
    at hr (pensieve.js?1512146626676:formatted:2802)
    at pensieve.js?1512146626676:formatted:3441
    at Object.fs (pensieve.js?1512146626676:formatted:4483)
    at t.diffObject (pensieve.js?1512146626676:formatted:8588)
    at t.objectDiffCommitMessage (pensieve.js?1512146626676:formatted:8607)
    at t.n.saveChange.A.default.debounce.leading (pensieve.js?1512146626676:formatted:72513)
    at r (pensieve.js?1512146626676:formatted:4583)
    at o (pensieve.js?1512146626676:formatted:4588)
    at t.f [as saveChange] (pensieve.js?1512146626676:formatted:4628)
    at onClick (pensieve.js?1512146626676:formatted:72637)
    at Object.r (pensieve.js?1512146626676:formatted:22875)
    at a (pensieve.js?1512146626676:formatted:22784)
    at Object.s [as executeDispatchesInOrder] (pensieve.js?1512146626676:formatted:22794)
    at h (pensieve.js?1512146626676:formatted:11318)
```

## Steps to Reproduce the Problem

1. Add a new schema field
1. Click 'Save Changes'

## Specifications

This only appears to be an issue in the bundled production version, not in development

## References

---

Before submitting this issue, please check that this issue is not a duplicate.
If there is another issue describing the same problem please add your
information to that issue's comments.

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Fixes #213

change-type: patch

### CODE REVIEW

File: src/util.js [hunk 1]
```diff
@@ -64,7 +64,7 @@ export const makeAnchorLink = string =>
 export const diffObject = (base, modified) => {
   const changes = []
   _.forEach(base, (value, key) => {
-    if (_(modified).has(key) && !_.isEqual(value, modified[key])) {
+    if (_.has(modified, key) && !_.isEqual(value, modified[key])) {
```
Comment (lurch) [inline src/util.js]: I'm not a lodash or eslint expert, but should the linter have been able to pick this up? (just asking out of curiosity...)
